language: node_js

services:
  - couchdb

node_js:
  - "stable"
sudo: false
firefox: "41.0.1"
script: npm run $COMMAND
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"

  - "export DEBUG=pouchdb:socket"

env:
  matrix:
  - COMMAND=test
  - CLIENT=selenium:firefox:41.0.1 COMMAND=test

branches:
  only:
  - master
