language: node_js

services:
  - couchdb

node_js:
  - "5"
sudo: false
addons:
  firefox: "41.0.1"
script: npm run $COMMAND
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

  - "export DEBUG=pouchdb:socket"
  - "npm install add-cors-to-couchdb"
  - "./node_modules/.bin/add-cors-to-couchdb"

env:
  matrix:
  - COMMAND=test
  - CLIENT=selenium:firefox:41.0.1 COMMAND=test

branches:
  only:
  - master
